#!/usr/bin/env bash
cd "$(dirname "$(readlink -f "$0")")" || exit 1

git pull

while true; do
	cat << EOF

Bashbot by Leon Schumacher
Last commit hash: $(git rev-parse --short HEAD)
Last commit mesg: $(
	git log --oneline -2 --format=%s | grep -v "Merge" \
	| sed 1q | tr -d '\n'
)
Now starting...

EOF
	bash "lib/main"
done
